#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;
		ct state vmap { invalid : drop, established : accept, related : accept }
		iif "lo" accept
		tcp dport { 22, 80, 443 } accept
		meta l4proto ipv6-icmp accept
		meta l4proto icmp accept
	}
}
