#!/bin/sh
# SPDX-License-Identifier: MIT
# =============================================================================
# eduVPN posture-gated server — first-boot provisioning
# =============================================================================
# Runs ONCE (guarded by a sentinel) via the eduvpn-first-boot.service oneshot.
# Steps:
#   1. Run the real eduVPN deploy_debian.sh non-interactively.
#   2. Bootstrap trust against step-ca and install the root in the trust store.
#   3. Replace the deploy's self-signed TLS cert with a step-ca-issued one.
#   4. Drop the CA bundle and inject the Apache mTLS snippet into the vhost.
#   5. Overlay the 5 patched vpn-user-portal files (native posture gate).
#   6. Inject the PostureCheck config pointing at the Wazuh Manager API.
#   7. Reset the demo user to a KNOWN password for headless testing.
#   8. Restart Apache + php-fpm.
#
# NOTE: deploy_debian.sh has no `set -e` and some sub-steps (nftables/WireGuard)
# may fail harmlessly in a container — the portal still comes up. Those steps are
# individually guarded with `|| …` below; everything else is critical.
#
# `set -e` guarantees a failed critical step aborts BEFORE the sentinel is
# written, so systemd re-runs first-boot on the next start instead of leaving a
# permanently half-provisioned container (no mTLS/posture wiring).
# =============================================================================
set -eu

SENTINEL=/var/lib/eduvpn-first-boot.done
[ -f "$SENTINEL" ] && { echo "[first-boot] already provisioned; nothing to do"; exit 0; }

# Escape a value for embedding inside a PHP single-quoted string literal
# (only \ and ' are special there): \ -> \\ , ' -> \'.
php_squote() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e "s/'/\\\\'/g"; }

# Central config — passed in from .env via compose (PassEnvironment); the values
# after :- are the committed demo defaults so first-boot still works standalone.
FQDN="${VPN_FQDN:-vpn.local}"
PKI=/pki
OVERLAY=/opt/posture-overlay
CA_URL=https://ca-server:9000
CA_PASSWORD="${CA_PASSWORD:-eduvpn-demo-ca-password}"
WAZUH_API_USER="${WAZUH_API_USER:-wazuh-wui}"
WAZUH_API_PASS="${WAZUH_API_PASS:-MyS3cr37P450r.*-}"

# Demo user credentials (KNOWN, for the headless OAuth demo). CHANGE FOR PROD.
DEMO_USER="${DEMO_USER:-vpn}"
DEMO_PASS="${DEMO_PASS:-admin}"

echo "[first-boot] ===== 1. running eduVPN deploy_debian.sh (FQDN=$FQDN) ====="
cd /opt/eduvpn-deploy || exit 1
# Prompts: DNS name, external interface, weekly auto-update? -> vpn.local, eth0, n
printf '%s\neth0\nn\n' "$FQDN" | ./deploy_debian.sh || \
    echo "[first-boot] deploy_debian.sh returned non-zero (continuing — see note above)"

echo "[first-boot] ===== 2. bootstrapping trust against step-ca ====="
FP="$(cat "$PKI/root_ca.fingerprint")"
step ca bootstrap --ca-url "$CA_URL" --fingerprint "$FP" --install --force

echo "[first-boot] ===== 3. requesting server TLS cert (SAN $FQDN) ====="
printf '%s' "$CA_PASSWORD" > /tmp/ca.pw
step ca certificate "$FQDN" \
    "/etc/ssl/certs/${FQDN}.crt" "/etc/ssl/private/${FQDN}.key" \
    --san "$FQDN" --provisioner admin --provisioner-password-file /tmp/ca.pw --force
rm -f /tmp/ca.pw
# Apache's vhost already points at these paths (deploy put a self-signed one there).

echo "[first-boot] ===== 4. installing CA bundle + Apache mTLS snippet ====="
mkdir -p /etc/eduvpn-mtls
cp "$PKI/ca-bundle.crt" /etc/eduvpn-mtls/ca-bundle.crt
VHOST="/etc/apache2/sites-available/${FQDN}.conf"
# Insert the snippet just before the closing tag of the *:443 VirtualHost
# (which is the last </VirtualHost> in the deploy-generated file).
LAST="$(grep -n '</VirtualHost>' "$VHOST" | tail -1 | cut -d: -f1)"
[ -n "$LAST" ] || { echo "[first-boot] FATAL: no </VirtualHost> found in $VHOST"; exit 1; }
{
    head -n "$((LAST - 1))" "$VHOST"
    cat "$OVERLAY/apache-mtls-snippet.conf"
    tail -n "+${LAST}" "$VHOST"
} > "${VHOST}.new"
mv "${VHOST}.new" "$VHOST"

echo "[first-boot] ===== 5. overlaying posture-check portal files ====="
# The Debian package does NOT use the source-repo layout. PHP classes live under
# /usr/share/php/Vpn/Portal (loaded by an autogenerated classmap autoloader);
# only web/api.php lives under /usr/share/vpn-user-portal/web. So we map the
# overlay accordingly rather than copying into a (non-existent) src/ tree.
OV="$OVERLAY/vpn-user-portal"
PHPDIR=/usr/share/php/Vpn/Portal
WEBDIR=/usr/share/vpn-user-portal/web

# 5a. Modified classes already present in the classmap → drop-in replace.
cp "$OV/src/Cfg/Config.php"             "$PHPDIR/Cfg/Config.php"
cp "$OV/src/Http/VpnApiThreeModule.php" "$PHPDIR/Http/VpnApiThreeModule.php"

# 5b. New posture classes.
cp "$OV/src/PostureChecker.php"         "$PHPDIR/PostureChecker.php"
cp "$OV/src/Cfg/PostureCheckConfig.php" "$PHPDIR/Cfg/PostureCheckConfig.php"

# 5c. Register the new classes — the Debian classmap autoloader is autogenerated
#     and does not know about them. A supplementary spl_autoload_register keeps
#     the generated file untouched.
if ! grep -q 'eduVPNextension posture-check classes' "$PHPDIR/autoload.php"; then
    cat >> "$PHPDIR/autoload.php" <<'PHPAL'

// eduVPNextension posture-check classes (not in the autogenerated classmap)
spl_autoload_register(function ($class) {
    static $m = [
        'Vpn\\Portal\\PostureChecker' => '/usr/share/php/Vpn/Portal/PostureChecker.php',
        'Vpn\\Portal\\PostureResult' => '/usr/share/php/Vpn/Portal/PostureChecker.php',
        'Vpn\\Portal\\WazuhApiException' => '/usr/share/php/Vpn/Portal/PostureChecker.php',
        'Vpn\\Portal\\Cfg\\PostureCheckConfig' => '/usr/share/php/Vpn/Portal/Cfg/PostureCheckConfig.php',
    ];
    if (isset($m[$class])) { require_once $m[$class]; }
});
PHPAL
fi

# 5d. api.php is a bootstrap entry point (not autoloaded). Use the overlay
#     version but keep the Debian classmap autoloader require (the package has
#     no composer vendor/autoload.php).
cp "$OV/web/api.php" "$WEBDIR/api.php"
sed -i "s#^require_once .*/vendor/autoload.php.*#require_once '/usr/share/php/Vpn/Portal/autoload.php';#" "$WEBDIR/api.php"

# 5e. Syntax-check the overlaid PHP.
if command -v php >/dev/null 2>&1; then
    for f in "$PHPDIR/Cfg/Config.php" "$PHPDIR/Http/VpnApiThreeModule.php" \
             "$PHPDIR/PostureChecker.php" "$PHPDIR/Cfg/PostureCheckConfig.php" \
             "$WEBDIR/api.php"; do
        php -l "$f" >/dev/null 2>&1 || echo "[first-boot] WARNING: php -l failed for $f"
    done
fi

echo "[first-boot] ===== 6. injecting PostureCheck config ====="
CONFIG=/etc/vpn-user-portal/config.php
# Escape the credentials for the PHP single-quoted string context so a password
# containing ' or \ can't corrupt (or inject into) config.php.
WAZUH_API_USER_PHP="$(php_squote "$WAZUH_API_USER")"
WAZUH_API_PASS_PHP="$(php_squote "$WAZUH_API_PASS")"
# Unquoted heredoc so the (already-escaped) Wazuh API credentials interpolate.
cat > /tmp/posture.php <<PHP

    // --- mTLS Device Posture Check (added by eduVPNextension) ---
    // Present => every /v3/connect requires a valid device cert AND an active
    // Wazuh agent. DEMO credentials below — CHANGE FOR PRODUCTION.
    'PostureCheck' => [
        'wazuhApiUrl' => 'https://wazuh.manager:55000',
        'wazuhUser' => '${WAZUH_API_USER_PHP}',
        'wazuhPass' => '${WAZUH_API_PASS_PHP}',
        'wazuhCaCert' => '',   // empty = skip Wazuh API TLS verify (internal net)
        'scaMinScore' => 0,    // 0 = agent-active check only
    ],

    // Close the browser-portal download path. The posture gate lives in the
    // API module (/v3/connect); the portal's own "download a configuration"
    // form calls ConnectionManager::connect() directly and is NOT gated, and
    // it hands out a config with the private key already in it. Upstream's
    // default is 3, so leaving this unset would let anyone with the portal
    // password obtain a working tunnel without a device certificate — exactly
    // what this project claims to prevent. 0 = VPN apps only.
    'maxActiveConfigurations' => 0,
PHP
# Insert the block immediately after the top-level `return [`.
sed -i "/^return \[/r /tmp/posture.php" "$CONFIG"
rm -f /tmp/posture.php
# The whole point of this container is fail-closed posture enforcement: if the
# block did NOT land (config format drift => sed no-op), the portal would come
# up with the gate silently disabled. Refuse to finish in that state.
grep -q "'PostureCheck'" "$CONFIG" || {
    echo "[first-boot] FATAL: PostureCheck config injection failed (gate would be disabled)"; exit 1; }
# Same reasoning for the portal download path: if this did not land, the ungated
# browser form is live and the fail-closed claim is false.
grep -q "'maxActiveConfigurations' => 0" "$CONFIG" || {
    echo "[first-boot] FATAL: maxActiveConfigurations injection failed (ungated portal downloads would be enabled)"; exit 1; }

echo "[first-boot] ===== 7. resetting demo user ($DEMO_USER) to known password ====="
# deploy created $DEMO_USER with a random password — reset it to the demo one.
sudo -u www-data vpn-user-portal-account --delete "$DEMO_USER" 2>/dev/null || true
sudo -u www-data vpn-user-portal-account --add "$DEMO_USER" --password "$DEMO_PASS"

echo "[first-boot] ===== 8. starting services (vpn-daemon, php-fpm, Apache) ====="
# vpn-daemon manages the WireGuard peers; the portal talks to it on :41194 to
# issue a config. Without it a passing posture check still 500s at /v3/connect.
systemctl enable --now vpn-daemon || echo "[first-boot] WARNING: vpn-daemon start failed"
systemctl restart 'php*-fpm' 2>/dev/null || true
# Apache serving the portal is load-bearing — a failed restart means no portal,
# so fail (and retry next boot) rather than record a bogus success.
systemctl restart apache2 || { echo "[first-boot] FATAL: apache2 restart failed"; exit 1; }

touch "$SENTINEL"
echo "[first-boot] DONE — portal should be reachable at https://${FQDN}/"
